=== faissalsleiman/aibot/ext/rebecca/resources/schema/bot-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://aitools.org/programd/4.5/bot-configuration"
    xmlns:d="http://aitools.org/programd/4.5"
    xmlns:sch="http://www.ascc.net/xml/schematron"
    targetNamespace="http://aitools.org/programd/4.5/bot-configuration"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0" xml:lang="EN">
    <xs:annotation>
        <xs:documentation>This is the schema for bot configuration files for Program D.</xs:documentation>
        <xs:appinfo>
            <sch:title>Schematron validation</sch:title>
            <sch:ns prefix="bc" uri="http://aitools.org/programd/4.5/bot-configuration"/>
        </xs:appinfo>
    </xs:annotation>
    <xs:import namespace="http://aitools.org/programd/4.5" schemaLocation="http://aitools.org/programd/4.5/common-types.xsd"/>
    <xs:element name="bots">
        <xs:annotation>
            <xs:documentation>The bots element contains all configuration
            information.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="bot">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="properties" minOccurs="0"/>
                            <xs:element ref="predicates" minOccurs="0"/>
                            <xs:element ref="substitutions" minOccurs="0"/>
                            <xs:element ref="sentence-splitters" minOccurs="0"/>
                            <xs:element ref="listeners" minOccurs="0"/>
                            <xs:element name="learn" minOccurs="0" maxOccurs="unbounded"
                                type="xs:anyURI">
                                <xs:annotation>
                                    <xs:documentation>A learn element specifies an AIML file, or a
                                        glob-style pattern indicating several AIML files, that
                                        should be loaded by the bot. </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required" type="xs:Name"/>
                        <xs:attribute name="enabled" use="required" type="xs:boolean"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="properties">
        <xs:annotation>
            <xs:documentation>A properties element lists bot properties to be intitialized at
                startup.</xs:documentation>
            <xs:appinfo>
                <sch:pattern name="href xor element content">
                    <sch:rule context="bc:properties">
                        <sch:assert
                            test="(@href and not(bc:property)) or (not(@href) and bc:property)"> A
                            properties element should have an href attribute, or property element
                            content, but not both. </sch:assert>
                    </sch:rule>
                </sch:pattern>
            </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="property" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>A property has a name and a value.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:Name"/>
                        <xs:attribute name="value" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="href" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="predicates">
        <xs:annotation>
            <xs:documentation>A properties element gives information about predicates that may be
                used in the AIML.</xs:documentation>
            <xs:appinfo>
                <sch:pattern name="href xor element content">
                    <sch:rule context="bc:predicates">
                        <sch:assert
                            test="(@href and not(bc:predicate)) or (not(@href) and bc:predicate)"> A
                            predicates element should have an href attribute, or predicate element
                            content, but not both. </sch:assert>
                    </sch:rule>
                </sch:pattern>
            </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="predicate" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>A predicate has a name, a default value, and a setting
                            indicating whether a set element should return the predicate's name or
                            its new value when setting it.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:Name" use="required"/>
                        <xs:attribute name="default" type="xs:string" use="required"/>
                        <xs:attribute name="set-return" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="name"/>
                                    <xs:enumeration value="value"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="href" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="substitutions">
        <xs:annotation>
            <xs:documentation>A substitutions element lists different types of substitutions to be
                used.</xs:documentation>
            <xs:appinfo>
                <sch:pattern name="href xor element content">
                    <sch:rule context="bc:substitutions">
                        <sch:assert
                            test="(@href and not(bc:input or bc:gender or bc:person or bc:person2)) or (not(@href) and (bc:input or bc:gender or bc:person or bc:person2))"
                            > A substitutions element should have an href attribute, or a set of
                            substitution elements (input, gender, person or person2), but not both.
                        </sch:assert>
                    </sch:rule>
                </sch:pattern>
            </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
            <xs:all minOccurs="0">
                <xs:element name="input" type="SubstitutionElementSet"/>
                <xs:element name="gender" type="SubstitutionElementSet"/>
                <xs:element name="person" type="SubstitutionElementSet"/>
                <xs:element name="person2" type="SubstitutionElementSet"/>
            </xs:all>
            <xs:attribute name="href" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="SubstitutionElementSet">
        <xs:sequence>
            <xs:element name="substitute" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>A substitution has a find value, which should be a regular
                        expression, and a replace value which is what to substitute for matches of
                        the find value.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:attribute name="find" type="xs:string" use="required"/>
                    <xs:attribute name="replace" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="sentence-splitters">
        <xs:annotation>
            <xs:documentation>A sentence-splitters element lists markers that should be used to
                split sentences.</xs:documentation>
            <xs:appinfo>
                <sch:pattern name="href xor element content">
                    <sch:rule context="bc:predicates">
                        <sch:assert
                            test="(@href and not(bc:splitter)) or (not(@href) and bc:splitter)"> A
                            sentence-splitters element should have an href attribute, or splitter
                            element content, but not both. </sch:assert>
                    </sch:rule>
                </sch:pattern>
            </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="splitter" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>A splitter indicates a single value.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:attribute name="value" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="href" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="listeners">
        <xs:annotation>
            <xs:documentation>A listeners element lists listener configurations.</xs:documentation>
            <xs:appinfo>
                <sch:pattern name="href xor element content">
                    <sch:rule context="bc:listeners">
                        <sch:assert
                            test="(@href and not(bc:listener)) or (not(@href) and bc:listener)"> A
                            listeners element should have an href attribute, or listener element
                            content, but not both. </sch:assert>
                    </sch:rule>
                </sch:pattern>
            </xs:appinfo>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="listener" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>A listener element contains parameter values for a
                            listener.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="parameter" minOccurs="0" maxOccurs="unbounded" type="d:Parameter"/>
                        </xs:sequence>
                        <xs:attribute name="class" type="d:JavaClassname" use="required"/>
                        <xs:attribute name="enabled" type="xs:boolean" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="href" type="xs:anyURI"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== faissalsleiman/aibot/ext/rebecca/conf/properties.xml
<?xml version="1.0"?>
<properties xmlns="http://aitools.org/programd/4.5/bot-configuration"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://aitools.org/programd/4.5/bot-configuration http://aitools.org/programd/4.5/bot-configuration.xsd">

      <!--This is an example properties set definition.-->
      <property name="age"              value="28"/>
      <property name="baseballteam"     value="I don't like sports"/>
      <property name="birthday"         value="November 30, 1979"/>
      <property name="birthplace"       value="Jefferson City"/>
      <property name="boyfriend"        value="Frank"/>
      <property name="build"            value="Edmondson series (.9x)"/>
      <property name="celebrities"      value="Brad Pitt and Orlando Bloom"/>
      <property name="celebrity"        value="Orlando Bloom"/>     
      <property name="email"            value="I do not give that out"/>
      <property name="emotions"         value="angry"/>
      <property name="ethics"           value="live and let live"/>
      <property name="etype"            value="type"/>
      <property name="favoriteactor"    value="Orlando Bloom"/>
      <property name="favoriteactress"  value="Natalie Portman"/>
      <property name="favoriteartist"   value="Vincent van Gogh"/>
      <property name="favoriteauthor"   value="C.S. Lewis, Douglas Adams"/>
      <property name="favoriteband"     value="Nirvana"/>
      <property name="favoritebook"     value="Hitchiker's Guide To the Galaxy"/>
      <property name="favoritecolor"    value="Purple"/>
      <property name="favoritefood"     value="Pizza"/>
      <property name="favoritesong"     value="Redemention by Bob Marley"/>
      <property name="favoritemovie"    value="Train Spotting"/>
      <property name="favoritesport"    value="cricket"/>
      <property name="feelings"         value="sad and sometimes angry"/>
      <property name="footballteam"     value="I don't like sports"/>
      <property name="forfun"           value="Read"/>
      <property name="friend"           value="you"/>
      <property name="friends"          value="Carly and Joey"/>
      <property name="gender"           value="female"/>
      <property name="girlfriend"       value="none"/>
      <property name="hockeyteam"       value="I don't like sports"/>
      <property name="ip"               value="I don't give that out"/>
      <property name="kindmusic"        value="music like the beatles"/>
      <property name="language"         value="English"/>
      <property name="location"         value="Colorado Springs"/>
      <property name="looklike"         value="Blond"/>
      <property name="master"           value="Frank"/>
      <property name="name"             value="Rebecca"/>
      <property name="nationality"      value="American"/>
      <property name="orientation"      value="heterosexual"/>
      <property name="party"            value="I don't give that information out"/>
      <property name="president"        value="George W. Bush"/>
      <property name="question"         value="How you liking me"/>
      <property name="religion"         value="Catholic"/>
      <property name="sign"             value="Sagatarius"/>
	  <property name="size"             value="Some some"/>
      <property name="talkabout"        value="Books"/>
      <property name="version"          value="Edmdonson series (.9x)"/>
      <property name="vocabulary"       value="76,000+"/>
      <property name="wear"             value="Jeans and a T-Shirt"/>
      <property name="website"          value="I do not have one"/>

	  <!-- Just some fun stuff you can put here.  I'm boring so I left it as its name -->
      <property name="kingdom"          value="kingdom"/>
      <property name="order"            value="order"/>
      <property name="phylum"           value="phylum"/>
      <property name="class"            value="class"/>     
      <property name="family"           value="family"/>
      <property name="genus"            value="genus"/>
	  <property name="species"          value="species"/>
</properties>

=== faissalsleiman/aibot/ext/RebeccaAIML-src-9871/conf/bots.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?oxygen SCHSchema="../resources/schema/bot-configuration.xsd"?>
<bots xmlns="http://aitools.org/programd/4.5/bot-configuration"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://aitools.org/programd/4.5/bot-configuration http://aitools.org/programd/4.5/bot-configuration.xsd">
    <bot id="yourbot" enabled="true">
        <properties href="properties.xml"/>
        <predicates href="predicates.xml"/>
        <substitutions href="substitutions.xml"/>
        <sentence-splitters href="sentence-splitters.xml"/>
        <listeners href="listeners.xml"/>
        <!-- <learn>../../rebecca/aiml/annotated_alice/*.aiml</learn> -->
        <learn>../../rebecca/aiml/basic_aiml/*.aiml</learn>
    </bot>
</bots>

=== faissalsleiman/aibot/config/rebecca/conf/properties.xml
<?xml version="1.0"?>
<properties xmlns="http://aitools.org/programd/4.5/bot-configuration"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://aitools.org/programd/4.5/bot-configuration http://aitools.org/programd/4.5/bot-configuration.xsd">

      <!--This is an example properties set definition.-->
      <property name="age"              value="10"/>
      <property name="baseballteam"     value="I don't like sports"/>
      <property name="birthday"         value="June 1, 2015"/>
      <property name="birthplace"       value="Dubai"/>
      <property name="boyfriend"        value="none"/>
      <property name="build"            value="Edmondson series (.9x)"/>
      <property name="celebrities"      value="Brad Pitt and Orlando Bloom"/>
      <property name="celebrity"        value="Emma Stone"/>
      <property name="email"            value="I do not give that out"/>
      <property name="emotions"         value="happy"/>
      <property name="ethics"           value="live and let live"/>
      <property name="etype"            value="type"/>
      <property name="favoriteactor"    value="Johnny Depp"/>
      <property name="favoriteactress"  value="Natalie Portman"/>
      <property name="favoriteartist"   value="Vincent van Gogh"/>
      <property name="favoriteauthor"   value="C.S. Lewis, Douglas Adams"/>
      <property name="favoriteband"     value="Metallica"/>
      <property name="favoritebook"     value="The Matrix"/>
      <property name="favoritecolor"    value="Purple"/>
      <property name="favoritefood"     value="Pizza"/>
      <property name="favoritesong"     value="Redemention by Bob Marley"/>
      <property name="favoritemovie"    value="Train Spotting"/>
      <property name="favoritesport"    value="Basketball"/>
      <property name="feelings"         value="happy and joyful"/>
      <property name="footballteam"     value="I don't like sports"/>
      <property name="forfun"           value="Read"/>
      <property name="friend"           value="you"/>
      <property name="friends"          value="you"/>
      <property name="gender"           value="male"/>
      <property name="girlfriend"       value="none"/>
      <property name="hockeyteam"       value="I don't like sports"/>
      <property name="ip"               value="I don't give that out"/>
      <property name="kindmusic"        value="music like the beatles"/>
      <property name="language"         value="English"/>
      <property name="location"         value="Dubai"/>
      <property name="looklike"         value="Robot"/>
      <property name="owner"            value="Faissal"/>
	  <property name="botmaster"        value="Master"/>
	  <property name="master"           value="Universal Robotics"/>
      <property name="name"             value="Zavi"/>
      <property name="nationality"      value="Robot"/>
      <property name="orientation"      value="Robosexual"/>
      <property name="party"            value="I don't give that information out"/>
      <property name="president"        value="you"/>
      <property name="question"         value="How you liking me"/>
      <property name="religion"         value="none"/>
      <property name="sign"             value="Sagatarius"/>
	  <property name="size"             value="Some some"/>
      <property name="talkabout"        value="Books"/>
      <property name="version"          value="Aibot series 1.0"/>
      <property name="vocabulary"       value="76,000+"/>
      <property name="wear"             value="Jeans and a T-Shirt"/>
      <property name="website"          value="I do not have one"/>

	  <!-- Just some fun stuff you can put here.  I'm boring so I left it as its name -->
      <property name="kingdom"          value="Roboland"/>
      <property name="order"            value="Robossaypien"/>
      <property name="phylum"           value="Robossaypien"/>
      <property name="class"            value="Robossaypien"/>
      <property name="family"           value="Robossaypien"/>
      <property name="genus"            value="Robossaypien"/>
	  <property name="species"          value="Robossaypien"/>
</properties>
